# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dashboard-vars

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd ./src/Dashboard
    npm install
    npm run build
    zip -r '$(Build.ArtifactStagingDirectory)/package.zip' ./build/*
  displayName: 'npm install, build and zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Internal Consumption(ef4a11cd-7f45-41ab-b4a3-02776b287779)'
    appType: 'webApp'
    WebAppName: 'serverlessdemodashboard'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/package.zip'
